name: Build AmneziaWG Packages

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_env:
          - tag: "23.05.3"   # стабильный релиз вместо SNAPSHOT
            pkgarch: aarch64_cortex-a53_neon-vfpv4
            target: ipq53xx
            subtarget: generic

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: Setup feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> feeds.conf

      - name: Download default config
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          make defconfig

      - name: Build toolchain
        run: |
          make tools/install -i -j$(nproc)
          make toolchain/install -i -j$(nproc)

      - name: Build packages
        run: |
          make package/kmod-amneziawg/{clean,download,prepare,compile} V=s
          make package/amneziawg-tools/{clean,download,prepare,compile} V=s
          make package/luci-app-amneziawg/{clean,download,prepare,compile} V=s

      - name: Collect artifacts
        run: |
          mkdir -p awgrelease
          cp bin/packages/${{ matrix.build_env.pkgarch }}/awgopenwrt/*.ipk awgrelease/ || true
          cp bin/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/packages/kmod-amneziawg_*.ipk awgrelease/ || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-packages
          path: awgrelease/*.ipk
